#!/bin/bash
# Linear Include Processor
# Processes <!-- include start xxx --> and <!-- include end xxx --> tags
# Clean, fast template system for SatoshiHost network sites

echo "🔨 Building HTML files with includes..."

# Function to process includes in a file - linear single pass
process_includes() {
    local input_file="$1"
    local output_file="$2"
    local temp_file=$(mktemp)
    
    echo "📄 Processing: $input_file → $output_file"
    
    # Add warning header to output file
    template_name=$(basename "$input_file")
    cat > "$temp_file" << EOF
<!-- ⚠️  WARNING: This file is AUTO-GENERATED by build.sh ⚠️ -->
<!-- 🚨 DO NOT EDIT THIS FILE DIRECTLY! 🚨 -->
<!-- -->
<!-- ✏️  To make changes, edit the template file instead: -->
<!-- 📁 templates/$template_name -->
<!-- -->
<!-- 🔧 Then run: ./build.sh -->
<!-- ⚠️  All direct edits to this file will be LOST! ⚠️ -->
<!-- ================================================================ -->

EOF
    
    # Process file line by line
    local in_include=false
    local include_name=""
    
    while IFS= read -r line; do
        # Check for include start tag
        if [[ "$line" =~ \<!--[[:space:]]*include[[:space:]]+start[[:space:]]+([^[:space:]]+)[[:space:]]*--\> ]]; then
            include_name="${BASH_REMATCH[1]}"
            in_include=true
            echo "  📎 Including: $include_name"
            
            # Add the start comment
            echo "$line" >> "$temp_file"
            
            # Add the include file content
            include_path="includes/$include_name"
            
            if [[ -f "$include_path" ]]; then
                cat "$include_path" >> "$temp_file"
            else
                echo "  ⚠️  Include file not found: $include_path"
                echo "<!-- ERROR: Include file not found: $include_path -->" >> "$temp_file"
            fi
            
        # Check for include end tag
        elif [[ "$line" =~ \<!--[[:space:]]*include[[:space:]]+end[[:space:]]+([^[:space:]]+)[[:space:]]*--\> ]]; then
            end_include_name="${BASH_REMATCH[1]}"
            
            if [[ "$end_include_name" == "$include_name" ]]; then
                # Add the end comment
                echo "$line" >> "$temp_file"
                in_include=false
                include_name=""
            else
                echo "  ⚠️  Mismatched include tags: started with '$include_name' but ended with '$end_include_name'"
                echo "$line" >> "$temp_file"
            fi
            
        # Regular line - only add if we're not inside an include block
        elif [[ "$in_include" == false ]]; then
            echo "$line" >> "$temp_file"
        fi
        # If we're inside an include block, skip the line (it gets replaced by include content)
        
    done < "$input_file"
    
    # Move final result to output
    mv "$temp_file" "$output_file"
    echo "  ✅ Built: $output_file"
}

# Process all HTML files with include tags
processed_count=0

# Find and process HTML files that contain include tags
for htmlfile in *.html; do
    if [[ -f "$htmlfile" ]] && grep -q "include start" "$htmlfile"; then
        # Create backup
        cp "$htmlfile" "${htmlfile}.bak"
        
        # Process includes in place  
        process_includes "$htmlfile" "$htmlfile"
        ((processed_count++))
    fi
done

if [[ $processed_count -eq 0 ]]; then
    echo "📁 No HTML files with includes found"
    echo "💡 Add include tags to HTML files like: \u003c!-- include start header.html --\u003e"
else
    echo ""
    echo "🎉 Build complete! Updated $processed_count HTML file(s)"
    echo ""
    echo "📝 Include syntax:"
    echo "   \u003c!-- include start header.html --\u003e"
    echo "   \u003c!-- include end header.html --\u003e"
    echo ""
    echo "📂 Directory structure:"
    echo "   includes/           - Shared HTML snippets (header, footer, sidebars)"
    echo "   *.html              - Your pages (edit these directly)"
    echo "   *.html.bak          - Automatic backups created during build"
fi

# Ensure script exits with success
exit 0

